version: "3.8"
services:
  neo4j:
    image: neo4j:5
    ports: ["7474:7474", "7687:7687"]
    environment:
      - NEO4J_AUTH=neo4j/localpassword
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j-data:/data
volumes:
  neo4j-data:
